import { Product } from './types/Products'

export const sampleProducts: Product[] = [
  {
    name: 'Nike Slime Shirts',
    slug: 'Nike Slime Shirts',
    category: 'Shirt',
    image: '../images/p1.jpg',
    price: 120,
    countInStock: 10,
    brand: 'Nike',
    rating: 4.5,
    numReviwews: 10,
    description: 'High Quality Shirt',
  },
  {
    name: 'Nike Slime Shirts',
    slug: 'Nike Slime Shirts',
    category: 'Shirt',
    image: '../images/p2.jpg',
    price: 120,
    countInStock: 10,
    brand: 'Nike',
    rating: 4.5,
    numReviwews: 10,
    description: 'High Quality Shirt',
  },
  {
    name: 'Nike Slime Shirts',
    slug: 'Nike Slime Shirts',
    category: 'Shirt',
    image: '../images/p3.jpg',
    price: 120,
    countInStock: 10,
    brand: 'Nike',
    rating: 4.5,
    numReviwews: 10,
    description: 'High Quality Shirt',
  },
  {
    name: 'Nike Slime Shirts',
    slug: 'Nike Slime Shirts',
    category: 'Shirt',
    image: '../images/p4.jpg',
    price: 120,
    countInStock: 10,
    brand: 'Nike',
    rating: 4.5,
    numReviwews: 10,
    description: 'High Quality Shirt',
  },
  {
    name: 'Nike Slime Shirts',
    slug: 'Nike Slime Shirts',
    category: 'Shirt',
    image: '../images/p1.jpg',
    price: 120,
    countInStock: 10,
    brand: 'Nike',
    rating: 4.5,
    numReviwews: 10,
    description: 'High Quality Shirt',
  },
  {
    name: 'Nike Slime Shirts',
    slug: 'Nike Slime Shirts',
    category: 'Shirt',
    image: '../images/p2.jpg',
    price: 120,
    countInStock: 10,
    brand: 'Nike',
    rating: 4.5,
    numReviwews: 10,
    description: 'High Quality Shirt',
  },
  {
    name: 'Nike Slime Shirts',
    slug: 'Nike Slime Shirts',
    category: 'Shirt',
    image: '../images/p3.jpg',
    price: 120,
    countInStock: 10,
    brand: 'Nike',
    rating: 4.5,
    numReviwews: 10,
    description: 'High Quality Shirt',
  },
  {
    name: 'Nike Slime Shirts',
    slug: 'Nike Slime Shirts',
    category: 'Shirt',
    image: '../images/p4.jpg',
    price: 120,
    countInStock: 10,
    brand: 'Nike',
    rating: 4.5,
    numReviwews: 10,
    description: 'High Quality Shirt',
  },
]
